services:
   hysteryale-fe:
      image: ${IMAGE_NAME}
      container_name: ${CONTAINER_NAME}
      ports:
         - '3005:3005'
      volumes:
         - /opt/hysteryale:/opt/hysteryale
         - /opt/hysteryale/hyster-yale-frontend/.env:/hysteryale-frontend/.env
      environment:
         - TZ=${TIMEZONE_HY}
